### ISSUE TITLE
conflicting dependancies

### ISSUE THREAD

**Issue by mrwatkinson** [cert-ee/cuckoo3#13]
There seems to be an issue with conflicting dependancies when running install.sh
cuckoo==3.0.0 seems to require sqlalchemy <1.4, >=1.3.13
cuckoo-common==0.1.0 seems to require sqlalchemy <1.5, >=1.4

because of these two different version assignemnts, you can not satisfy the dependancy requirements of both cuckoo-common and cuckoo 3 at the same time.

**Comment by amadisson** [comment]
Seems issue when updating existing version, fixed. 
cuckoo==3.0.1 require cuckoo-common>=0.1.2  and sqlalchemy <1.5, >=1.4
cuckoo-common>=0.1.2 require sqlalchemy <1.5, >=1.4
