### ISSUE TITLE
502 Bad Gateway nginx/1.18.0 (Ubuntu) when accessing port 8080 for web after running new install.sh

### ISSUE THREAD

**Issue by OzzyKampha** [cert-ee/cuckoo3#163]
**Describe the bug**
502 Bad Gateway
nginx/1.18.0 (Ubuntu) when accessing port 8080 for web

tried curl localhost:8080, same error, bot ngnx and uwsgi service running

**To Reproduce**
run the install.sh on new ubuntu. Try to access web gui, error

**Expected behavior**
The web gui should come up

** My Cuckoo version and operating system are::**
 Cuckoo 3.0.1, Ubuntu 22.04

**The log, error, files etc can be found at:**

**Comment by cert-ee-raidar** [comment]
@OzzyKampha 
Thank you for submitting the bug.
Did You run the Quickstart script from the web?
You mention install.sh script, which is still the old one.
What does your nginx error.log say?

**Comment by OzzyKampha** [comment]
Sorry about that, yes i ran the new quickstart script. 

` 38933#38933: *1 connect() failed (111: Unknown error) while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:9090", host: "localhost:8080"
`

**Comment by OzzyKampha** [comment]
I saw that the uwsgi service had exited

**Comment by cert-ee-raidar** [comment]
Did you get it to work now or still problems with uWSGI?

**Comment by OzzyKampha** [comment]
I got it working, had to restart the service

**Comment by cert-ee-raidar** [comment]
Good to hear!
If you want, you can share extra details.
If not, I will close this issue as resolved.

**Comment by cert-ee-raidar** [comment]
There was a bug in the quickstart where uwsgi was not restarted after enabling Cuckoo application after symlinking.
Should be fixed now.
