### ISSUE TITLE
vmcloack-qemubridge: command notfound

### ISSUE THREAD

**Issue by glatinone** [cert-ee/cuckoo3#172]
**Describe the bug**
i want to install cuckoo on my ubuntu 22.04, but when run command vmcloack-qemubridge got error, i have already update and install the vmcloack full package, also i already re-install, but still got the same problem

**To Reproduce**

**Expected behavior**

** My Cuckoo version and operating system are::**
 Cuckoo 3.0.1, Ubuntu 22.04

**The log, error, files etc can be found at:**
![image](https://github.com/user-attachments/assets/2f06b8c5-0072-4971-87ff-4f0916510ef3)

**Comment by cert-ee-raidar** [comment]
@glatinone ,

Did you install VMCloak under the root user?
The screenshot shows that you are logged in as `root`, but the command looks for the binary `vmcloak-qemuhelper` from under the user `cuckoo`.
We strongly advise against running both Cuckoo and using VMCloak as root.

**Comment by glatinone** [comment]
yes i'm install VMCloak under root user.

but i follow ur instruction to run all in one configuration refer to picture below.
![image](https://github.com/user-attachments/assets/429f5186-edd6-471a-8436-96219b9fcf31)

can u give me suggestion command to run step **Configuration VMCloak**

Thanks for help!

**Comment by cert-ee-raidar** [comment]
You need to install both Cuckoo3 and VMCloak under a non root user, such as `cuckoo`.
Please see [Installing VMCloak](https://cuckoo-hatch.cert.ee/static/docs/installing/vmcloak/#all-in-one-install) and [Installing Cuckoo3](https://cuckoo-hatch.cert.ee/static/docs/installing/cuckoo/).
You need sudo priviledges only for such steps that configure or modify system configurations

**Comment by glatinone** [comment]
thanks for the answer, and i'm follow ur suggestion to run command under non roon user. but now i found error when install win10base, please refed to image below. can u give me what need should to do ? Thanks before.
![image](https://github.com/user-attachments/assets/ee2887c1-b2d0-4c50-aaa4-aa2b50053dc6)

**Comment by cert-ee-raidar** [comment]
@glatinone 
Yes. VMCloak cannot create a new image if  qcow2 image with the sae
Me name exists.
Delete the image.

`rm /home/cuckoo/.vmcloak/image/win10base.qcow2`

**Comment by glatinone** [comment]
yeah i'm already remove it, but it still another error refered to images below.

![image](https://github.com/user-attachments/assets/fbaa82c3-3e26-41d8-bc99-12558f9bca61)

**Comment by glatinone** [comment]
Hi, i was searching and ask chatgpt for this command need requirement virtualization. fyi i have turn on virtualization on BIOS and install software needed but still showing value 0. is that means my device can't support for this cuckoo 3. Do you have any suggestions like using another virtual machine maybe ? Thanks Before! i appreciate your answer.

![image](https://github.com/user-attachments/assets/36a25a01-c568-4f15-839e-b2
ed5711fa02)

**Comment by cert-ee-raidar** [comment]
Either delete everything (users, folders) and use the [Quickstart](https://cuckoo-hatch.cert.ee/static/docs/installing/quickstart/#quickstart) script or follow all the steps, starting from [Manual](https://cuckoo-hatch.cert.ee/static/docs/installing/overview/#manual) installation.

Your current errors indicate you have not followed all installation guides properly.

Laa error occurs when you have not added cuckoo user to `kvm` group

**Comment by cert-ee-raidar** [comment]
> Hi, i was searching and ask chatgpt for this command need requirement virtualization. fyi i have turn on virtualization on BIOS and install software needed but still showing value 0. is that means my device can't support for this cuckoo 3. Do you have any suggestions like using another virtual machine maybe ? Thanks Before! i appreciate your answer.
> 
> ![image](https://github.com/user-attachments/assets/3d845879-fbde-4bca-ba4b-3b79303d3780)
> 

Unfortunately we do not cover guides on running Cuckoo3 inside virtual environments because the options are so many. 
If you want to use it inside a virtual environment, use Vagrant and libvirt.

**Comment by glatinone** [comment]
emm first thing first i using quickstart script and it still not worked, so i reinstall my vm to clean, and using Manual Installation and still have the same problem. is that cuckoo3 have full documentation for using Vagrant ? i really apreaciate it if do. Thanks

**Comment by cert-ee-raidar** [comment]
We do not have a documentation on how to use Vagrant, but since you are using ChatGPT, it can guide you through setting up the network interfaces and debugging Vagrant problems

I can share a Vagrantfile to get you started(you need libvirt system dependencies as well as vagrant libvirt plugin)
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Define the base box
  config.vm.box = "bento/ubuntu-22.04"

  # Configure the VM named 'testserver'
  config.vm.define "vmcloak-libvirt" do |vmcloak|

    # Network settings - Forward port 2222 on the host to port 22 on the guest VM
    vmcloak.vm.network "forwarded_port", guest: 443, host: 8443
    vmcloak.vm.network "forwarded_port", guest: 8080, host: 8081

    # Specify the provider-specific configuration (e.g., VirtualBox)
    vmcloak.vm.provider :libvirt do |vb|
      # Customize the VM (e.g., memory and CPU)
      vb.memory = "8192"
      vb.cpus = 4
      vb.driver = "kvm"
    end
    config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update && sudo apt-get dist-upgrade -y
    reboot
    SHELL
  end

  # Global SSH configuration
  config.ssh.username = "vagrant"
end
```
Since I don't want to turn issues into tutorials, I will close the issue since the original question was answered.
Please email us at cuckoo3[at]cert.ee if you need more assistance with setup. We can then add you to our chat channel.
