### ISSUE TITLE
Linux guest VM

### ISSUE THREAD

**Issue by PatocskaiErik** [cert-ee/cuckoo3#180]
Hi,
Unfortunately, I could only find documentation everywhere with a Windows Guest VM installation. I'd like to install Linux Guest (Ubuntu or Debian), but I couldn't find anything about it anywhere. Does the current version support Linux Guest installation? Or what is the best way to do this?

Thank you in advance!

**Comment by cert-ee-raidar** [comment]
Hey @PatocskaiErik 
Linux is not supported. It is in our roadmap though

**Comment by cert-ee-raidar** [comment]
Supported guests You can find at our [About Cuckoo3](https://cuckoo-hatch.cert.ee/static/docs/about/cuckoo/)
Also check out our [roadmap](https://github.com/orgs/cert-ee/projects/1)

**Comment by PatocskaiErik** [comment]
Thank you! :)

**Comment by cert-ee-raidar** [comment]
Duplicate of #119
