### ISSUE TITLE
Interactive detonation 

### ISSUE THREAD

**Issue by OzzyKampha** [cert-ee/cuckoo3#182]
## Proposed solution
I would like Interactive detonations, there Are multiple malware that need more to activate then running it. But also to Watch the detonation happening

Capev2 have done this with guacamole

**Comment by cert-ee-raidar** [comment]
Hey @OzzyKampha,

Thank you for the suggestion.

We currently do not have such a feature planned.
If we change our minds, it will appear on our roadmap.

I'm currently closing this as not planned.

But don't let this discourage you from suggesting new features and ideas.

**Comment by nicpenning** [comment]
I would really like this feature as well. It is a must for URL analysis. Phishing page detonation is a great use case for sandboxes.
