### ISSUE TITLE
Ambiguous Python version requirements in the docs

### ISSUE THREAD

**Issue by Cryss76** [cert-ee/cuckoo3#22]
There are two instances in the docs where a python version is specified.
- On [docs/src/introduction/cuckoo.md](https://github.com/cert-ee/cuckoo3/blob/0186c2dc08acc535be17775f6ab312d17d96a191/docs/src/introduction/cuckoo.md) It's stated that either python 3.6 or 3.8 will work.
- On [docs/src/installation/cuckoo.md](https://github.com/cert-ee/cuckoo3/blob/0186c2dc08acc535be17775f6ab312d17d96a191/docs/src/installation/cuckoo.md) is stated that any version >= python3.6 is fine.

So which one is it? and shouldn't support for python3.6 be dropped as It's EOL?

**Comment by amadisson** [comment]
Python 3.8 is best choice. 
Python 3.6 support should be dropped as soon need Python 3.10 support.
