### ISSUE TITLE
Conflicting Dependencies

### ISSUE THREAD

**Issue by C0WB0Y-Ducky** [cert-ee/cuckoo3#25]
Apologies in advance for the picture
![IMG_1882](https://user-images.githubusercontent.com/51971356/217075917-ec1dc4d2-f43a-4cf2-8589-1ef42b2f4c0c.JPG)

I was installing via the install.sh, ran into issues with hyperscan
i did a:
python3 -m pip install -UI pip
python3 -m pip install hyperscan
- Then I reran the install.sh and ran into the conflicting dependencies

**Comment by rboics** [comment]
Watching this closely, as I've also encountered the same issue.

**Comment by amadisson** [comment]
I updated sflock fork 3 days ago, it should be resolved.
