### ISSUE TITLE
Proxmox support

### ISSUE THREAD

**Issue by mrtnrdl** [cert-ee/cuckoo3#3]
With cuckoo 2, it was possible to let it run on proxmox (see https://www.trustedsec.com/blog/working-with-proxmox/) - i'd love to get cuckoo 3 to work with proxmox as well. 

I'll set up a new VM and start working on it asap - feel free to contact me if you are interested in that feature as well.

**Comment by gamer4life1** [comment]
+1 please!

**Comment by fldu** [comment]
@mrtnrdl I think this repo[1] might be an interesting lead to have this feature in cuckoo 3. 

[1]Github repo: https://github.com/snus-b/proxmoxcuckoo

**Comment by gamer4life1** [comment]
@mrtnrdl did you get any progress? Just wondering

**Comment by Cryss76** [comment]
Proxmox is now supported.
@amadisson pls close
