### ISSUE TITLE
Error when using ./install.sh

### ISSUE THREAD

**Issue by trangnt2304** [cert-ee/cuckoo3#30]
![image](https://user-images.githubusercontent.com/105774467/231712194-0d1f6a24-201d-456a-8c5d-b478b8a7b7f6.png)

I got this error when running `./install.sh`, can anyone help me please :(

**Comment by Cryss76** [comment]
This is a permissions problem check that `/opt/cuckoo3` is owned by the cuckoo user or that the cuckoo user is allowed to use the folder by any other means.

**Comment by rkivistik** [comment]
@Cryss76 answer is correct.
Closing the issue.
If the issue persists, please open a new issue.

**Comment by rkivistik** [comment]
@Cryss76 answer is correct.
Closing the issue.
If the issue persists, please open a new issue.
