### ISSUE TITLE
No module named 'hyperscan._hyperscan

### ISSUE THREAD

**Issue by 0x4hm3d** [cert-ee/cuckoo3#32]
Hello All,
I install cuckoo3 as the documentation and after running cuckoo -d, I got this error 

ERROR [cuckoo.runprocessing]: Failed to import plugins for worker. worker=post0 importpath=cuckoo.processing.post.eventconsumer abstractclass=<class 'cuckoo.processing.abtracts.EventConsumer'> error=Failed to import: cuckoo.processing.post.eventconsumer.patternsigs. Error: No module named 'hyperscan._hyperscan'
 ERROR [cuckoo.runprocessing]: Worker setup failed. See worker logs. workername=post0
ERROR [cuckoo.runprocessing]: Worker disconnected unexpectedly. workername=post0

I run the install.sh many times and all dependence installed without any error 
I run pip list to check the version and this is the list 

Package                        Version    Location
------------------------------ ---------- ------------------------
aiohttp                        3.8.4
aiohttp-sse                    2.1.0
aiohttp-sse-client             0.2.1
aiosignal                      1.3.1
alembic                        1.7.7
asgiref                        3.6.0
async-timeout                  4.0.2
attrs                          23.1.0
backports.zoneinfo             0.2.1
Brotli                         1.0.9
capstone                       3.0.5
certifi                        2022.12.7
cffi                           1.15.1
charset-normalizer             3.1.0
click                          8.1.3
colorama                       0.3.7
colorclass                     2.2.2
cryptography                   38.0.4
Cuckoo                         3.0.1      /opt/cuckoo3/core
Cuckoo-common                  0.1.1      /opt/cuckoo3/common
Cuckoo-machineries             0.1.0      /opt/cuckoo3/machineries
Cuckoo-node                    0.1.1      /opt/cuckoo3/node
Cuckoo-processing              0.1.1      /opt/cuckoo3/processing
Cuckoo-web                     0.1.2      /opt/cuckoo3/web
Deprecated                     1.2.13
Django                         4.2
django-ipware                  5.0.0
django-rest-framework          0.1.0
djangorestframework            3.14.0
dpkt                           1.9.8
easygui                        0.98.3
ecdsa                          0.18.0
elasticsearch                  7.17.9
elasticsearch-dsl              7.4.1
frozenlist                     1.3.3
future                         0.18.3
ghp-import                     2.1.0
greenlet                       2.0.2
HTTPReplay                     1.0.1
hyperscan                      0.3.2
idna                           3.4
importlib-metadata             6.4.1
importlib-resources            5.12.0
ipaddress                      1.0.23
Jinja2                         3.1.2
jsbeautifier                   1.6.2
jsonschema                     4.17.3
Mako                           1.2.4
Markdown                       3.3.7
MarkupSafe                     2.1.2
mergedeep                      1.3.4
mkdocs                         1.4.2
mkdocs-include-markdown-plugin 4.0.4
msoffcrypto-tool               5.0.1
multidict                      6.0.4
olefile                        0.46
oletools                       0.60.1
packaging                      23.1
pcodedmp                       1.2.6
peepdf                         0.4.2
pefile                         2022.5.30
Pillow                         3.2.0
pip                            20.0.2
pkg-resources                  0.0.0
pkgutil-resolve-name           1.3.10
protobuf                       3.20.3
psutil                         5.9.4
publicsuffixlist               0.9.4
pycparser                      2.21
pycryptodome                   3.17
pymisp                         2.4.170
pyparsing                      2.4.7
pyrsistent                     0.19.3
python-dateutil                2.8.2
python-magic                   0.4.12
pythonaes                      1.0
pytz                           2023.3
PyYAML                         6.0
pyyaml-env-tag                 0.1
requests                       2.28.2
roach                          1.0
setuptools                     58.0.0
SFlock                         1.0.3
six                            1.16.0
SQLAlchemy                     1.4.47
sqlparse                       0.4.3
suricatactl                    0.0.1.dev3
tabulate                       0.8.10
tlslite-ng                     0.7.6
typing-extensions              4.5.0
urllib3                        1.26.15
uWSGI                          2.0.21
VMCloak                        1.0
vt-py                          0.6.3
watchdog                       3.0.0
wheel                          0.40.0
wrapt                          1.15.0
yara-python                    4.2.3
yarl                           1.8.2
zipp                           3.15.0

there is anyone can help me to fix this issue 

Thanks

**Comment by amadisson** [comment]
Please read      » Installation »System dependencies

**Comment by 0x4hm3d** [comment]
I read it and all dependencies installed on the machine, for now what I missed,

**Comment by OzzyKampha** [comment]
Same problem here

**Comment by amadisson** [comment]
Make sure that can import hyperscan, try reinstall hyperscan wheel. 
Updated to latest to hyperscan 0.4.0 and works.

**Comment by OzzyKampha** [comment]
New error 
```pkg_resources.DistributionNotFound: The 'hyperscan==0.3.2' distribution was not found and is required by Cuckoo-processing
```

**Comment by 0x4hm3d** [comment]
after use hyperscan=0.4.0 got this error
pkg_resources.ContextualVersionConflict: (hyperscan 0.4.0 (/opt/cuckoo3/venv/lib/python3.8/site-packages), Requirement.parse('hyperscan==0.3.2'), {'Cuckoo-processing'})

**Comment by 0x4hm3d** [comment]
the solution is to go to /opt/cuckoo3$ cd /opt/cuckoo3/processing inside the env, change the version on hyperscan version on the setup.py to version 0.4.0 and after that run the install.sh again and after finishing the installation, RUN cuckoo -d the error will fix

**Comment by OzzyKampha** [comment]
Does not fix the problem

**Comment by trangnt2304** [comment]
> the solution is to go to /opt/cuckoo3$ cd /opt/cuckoo3/processing inside the env, change the version on hyperscan version on the setup.py to version 0.4.0 and after that run the install.sh again and after finishing the installation, RUN cuckoo -d the error will fix

This does not fix the problem for me.
