### ISSUE TITLE
No machines available

### ISSUE THREAD

**Issue by trangnt2304** [cert-ee/cuckoo3#36]
When I run "cuckoo -d" I got this error that it shows 0 machine. Can anyone help me please?

![image](https://user-images.githubusercontent.com/105774467/236131468-4d17dabd-b58d-451d-9114-41f542386d2d.png)
![image](https://user-images.githubusercontent.com/105774467/236131503-5b5746ee-d651-4aaa-8d48-c4bc9027fded.png)

**Comment by Cryss76** [comment]
The zero after machine(s) does not stand for the available amount of analysis machines.
This is sort of unintuitive and might be in fact a bug but what the number count is the amount of search constrains you add.

For example, if you untick "automatically select..." and add an os constraint the number will raise.

**Comment by trangnt2304** [comment]
Yes I can see it now, thank you
