### ISSUE TITLE
sqlite:////root/.cuckoocwd/cuckoo.db. Found version: 'No version table'. Latest version: ''.

### ISSUE THREAD

**Issue by jt361** [cert-ee/cuckoo3#38]
Does anyone know how to fix this? Thanks.

2023-05-30 14:56:24 INFO  [cuckoo.startup]: Starting Cuckoo. cwd=/root/.cuckoocwd
2023-05-30 14:56:24 INFO  [cuckoo.startup]: Loading configurations
2023-05-30 14:56:24 ERROR [cuckoo.common.log]: Failure during Cuckoo startup: Cuckoo database (cuckoodb) requires migration(s). sqlite:////root/.cuckoocwd/cuckoo.db. Found version: 'No version table'. Latest version: ''.
Stopping Cuckoo..
Failure during Cuckoo startup: Cuckoo database (cuckoodb) requires migration(s). sqlite:////root/.cuckoocwd/cuckoo.db. Found version: 'No version table'. Latest version: ''.

**Comment by Cryss76** [comment]
`cuckoomigrate database all`

**Comment by Cryss76** [comment]
@jt361 did this solve your issue?

**Comment by Cryss76** [comment]
@amadisson  pls close because of no reply

**Comment by geeksailor** [comment]
@Cryss76 I just got the same error trying to run C3. I ran `cuckoomigrate database all` and got the following error (abbreviated):

>FileNotFoundError: [Errno 2] No such file or directory: '
/home/.../venv/cuckoo3/common/cuckoo/common/data/dbmigrations/{safelistdb}{cuckoodb}/versions'
/home/.../venv/cuckoo3/core/cuckoo/data/dbmigrations/taskqueuedb/versions
2023-11-08 15:23:14 ERROR [cuckoo.common.log]: One or more migrations failed. Error during migration of 'cuckoodb'. Alembic exit code: 1, Error during migration of 'safelistdb'. Alembic exit code: 1, Error during migration of 'taskqueuedb'. Alembic exit code: 1
One or more migrations failed. Error during migration of 'cuckoodb'. Alembic exit code: 1, Error during migration of 'safelistdb'. Alembic exit code: 1, Error during migration of 'taskqueuedb'. Alembic exit code: 1

Were version files supposed to have been made as a part of the install process?

**Comment by geeksailor** [comment]
Looking through other comments I saw that someone was also having a database issue and was told to run 
> qlite3 ~/.cuckoocwd/operational/taskqueue.db .fullschema

My results were:
`sqlite3 ~/.cuckoocwd/operational/taskqueue.db .fullschema
CREATE TABLE alembic_version (
	version_num VARCHAR(32) NOT NULL, 
	CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);
/* No STAT tables available */
`
It looks like my results looks like the database was never populated. I'm looking around still to see if I can find a fix to this. Maybe try running some script or something in cuckoo directories that may not have ran initially. But no luck so far.

**Comment by geeksailor** [comment]
Tracing the various scripts, I managed to trace what looks like startup.py under `~/.cuckoocwd/conf/common/cuckoo/common` that imports from db.py in the same location. I reran setup.py under `~/.cuckoocwd/conf/common` and reran `sqlite3 ~/.cuckoocwd/operational/taskqueue.db .fullschema` now I'm seeing
>CREATE TABLE alembic_version (
	version_num VARCHAR(32) NOT NULL, 
	CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);
CREATE TABLE qeueudtasks (
	id VARCHAR(32) NOT NULL, 
	kind VARCHAR(15) NOT NULL, 
	created_on DATETIME NOT NULL, 
	analysis_id VARCHAR(15) NOT NULL, 
	priority INTEGER NOT NULL, 
	platform VARCHAR(255), 
	os_version VARCHAR(255), 
	_machine_tags VARCHAR(255), 
	_route TEXT, 
	dephash INTEGER NOT NULL, 
	scheduled BOOLEAN, 
	PRIMARY KEY (id)
);
/* No STAT tables available */

Now I'm seeing 
>....
DEBUG [cuckoo.node.startup]: Starting resultserver. listenip=192.168.30.101 listenport=2042 sockpath=/home/<>/.cuckoocwd/operational/sockets/resultserver.sock cwd=/home/<>/.cuckoocwd
.....
ERROR [cuckoo.common.log]: Failed to start resultserver on: 192.168.30.101:2042. [Errno 99] error while attempting to bind on address ('192.168.30.101', 2042): cannot assign requested address
.....
INFO  [cuckoo.node.resultserver]: Stopping resultserver..
Failed to start resultserver on: 192.168.30.101:2042. [Errno 99] error while attempting to bind on address ('192.168.30.101', 2042): cannot assign requested address
ERROR [cuckoo.common.log]: Failure during Cuckoo startup: Resultserver stopped unexpectedly
......
Failure during Cuckoo startup: Resultserver stopped unexpectedly
