### ISSUE TITLE
cuckoo css not finding ...

### ISSUE THREAD

**Issue by inventoramin** [cert-ee/cuckoo3#45]
after running, the UI is not working.
`cuckoo web --host 192.168.30.1 --port 8080` command respond:

![cuckoocss](https://github.com/cert-ee/cuckoo3/assets/30364703/3ebf31d3-a0e2-4d45-9959-a15e92cadd3e)

and this is the front: 

![cuckoo2](https://github.com/cert-ee/cuckoo3/assets/30364703/5efb4ccc-ef95-4ac9-a683-fdd0689d96c5)

**Comment by Cryss76** [comment]
you need to set `DEBUG = True` in `<cwd>/web/web_local_settings.py`

**Comment by inventoramin** [comment]
> you need to set `DEBUG = True` in `<cwd>/web/web_local_settings.py`

still the same problem :(

**Comment by inventoramin** [comment]
It was routing problem of nginx and uwsgi.
running nginx and going for 127.0.0.1:80 solve the UI problem
