### ISSUE TITLE
No API Call trace

### ISSUE THREAD

**Issue by SigmaStar** [cert-ee/cuckoo3#5]
It seems that there's no api call trace in report.json. Are there xchat channel available for chatting?

**Comment by heikipikker** [comment]
x-chat is only IRC client. We use Mattermost platform for chatting. You can download Mattermost client from https://mattermost.com/download/

**Comment by 0ssigeno** [comment]
Hey guys! There is any plan to support the dump of the entirety of API calls that the sample make?

**Comment by rkivistik** [comment]
@0ssigeno We are currently not planning to add functionality for dumping all API calls in the sample context.
We can consider adding API dumps based on user needs and after we have concluded they would indeed be sensible to implement and useful to the users.
For that please open a new issue describing which dumps you need and for what purpose.

To avoid mixing issues, this one will be closed.
