### ISSUE TITLE
tmstage and threemon source code

### ISSUE THREAD

**Issue by exofelipe** [cert-ee/cuckoo3#6]
Is it possible to include on the repository the sources of tmstage.exe and the threemon.sys driver? 

That way it's easier for the community to improve cuckoo monitoring and even adapt the monitor for other operating systems.

Thanks!

**Comment by heikipikker** [comment]
No, that makes also easier sandbox detection and development of anti-sandbox software.

**Comment by exofelipe** [comment]
But how can we help in the development of cuckoo for new platforms, and even in bypassing those anti-sandbox software, without those sources? 

Cuckoo always had the source codes for the detonation phase (https://github.com/cuckoosandbox/monitor). Can't at least the tmstage.exe source code be shared? It's written in golang without packers or anything, reversing it is very easy, it's more a matter of making easier to improve it, and changing small stuff before the execution starts (like we could do with cuckoo analyzer in the original cuckoo)
