### ISSUE TITLE
cant install ./common

### ISSUE THREAD

**Issue by Smartking1** [cert-ee/cuckoo3#60]
I am done installing the requirements to run Cuckoo but I cant locate the install.sh script. Is there any comand to be run after installing system requirements?

**Comment by Cryss76** [comment]
can you post the content of the cuckoo3 folder (or the folder you clone the repo in)?

**Comment by Smartking1** [comment]
I cloned the repo again and I found the script but the script is not running successfully.
I returns the error install of ./common failed

**Comment by Cryss76** [comment]
then post the logs containing the error message.

**Comment by Smartking1** [comment]
![cuckoo](https://github.com/cert-ee/cuckoo3/assets/67761118/e16c49fd-229f-4771-94bb-d1e1c52b1490)

**Comment by Cryss76** [comment]
Dont run pip as the root user, create a venv and update pip; then try again.

**Comment by Smartking1** [comment]
![cuckoo2](https://github.com/cert-ee/cuckoo3/assets/67761118/2acdde48-7f47-4506-a835-964fb25a0214)
![cuckoo3](https://github.com/cert-ee/cuckoo3/assets/67761118/01b20ded-7967-48ad-82e4-e06eb97cda56)

This is the error that I am getting

**Comment by amadisson** [comment]
"Could not resolve host github.com" so some requirements are not installed.

**Comment by Cryss76** [comment]
Also use the recommended python version 3.8.

**Comment by ar005** [comment]
@Smartking1 run these it solved the same issue for me
python3 -m pip install -UI pip
python3 -m pip install hyperscan
 ./install --user

As far as i understand this works because --user flag makes the install locally without superuser privileges, which is advised against in the repo.

**Comment by rkivistik** [comment]
@Smartking1 Has your issue been resolved?

**Comment by cert-ee-raidar** [comment]
Closing the issue due to inactivity and assuming issue resolved.
This thread contains all the solutions to fix the original problem
