### ISSUE TITLE
The event "Loads a driver" is misleading and/or incomplete

### ISSUE THREAD

**Issue by Cryss76** [cert-ee/cuckoo3#63]
When this event is triggered, it is represented in the report as a signature with an suspicious score (of 6).
The Signature also list the process `services.exe` as the only ioc.

Such an event can be very well malicious or legit. It heavily depends on what driver is loaded. The event doesn't show this crucial information and is therefore pretty useless and misleading. Furthermore the process name given as an ioc is not an ioc but part of the normal driver loading process.

**Comment by rkivistik** [comment]
@Cryss76 We will look into it as soon when we get the chance. 
Thank you for pointing out the issue

**Comment by cert-ee-raidar** [comment]
We will add more detailed information about various parts of Cuckoo in the future and we will mark this as one of the problem spots.

**Comment by cert-ee-raidar** [comment]
Added this to our roadmap for improving existing functionality #177 
Closing this issue.
