### ISSUE TITLE
certain pdf files can lead to peepdf creating a fatal error

### ISSUE THREAD

**Issue by Cryss76** [cert-ee/cuckoo3#64]
**Describe the bug**
On an PDF-file analysis one of  two Fatal errors can occur, which halts the whole analysis. This is triggered by certain pdf-files.
I can open the files normally without error and I don't know what property of the pdf causes the error.

**To Reproduce**

- Install Cuckoo and get it and its web app running
- go to the submit menu
- select a pdf-file
- click on configure analysis

**Expected behavior**
The analysis should continue normally, even if an error occurs during peepdf-analysis.

**My Cuckoo version and operating system are:**
 Cuckoo 3.0.1, Ubuntu 20.04

**The log, error, files etc can be found at:**
```
Analysis <id> identification processing cancelled by plugin: Identify.
Reason: Failed to unpack file: peepdf parsing failure: local variable 'pdfCrossRefEntry' referenced before assignment.
Unpacker: pdffile
```

```
Analysis <id> identification processing cancelled by plugin: Identify.
Reason: Failed to unpack file: peepdf parsing failure: slice indices must be integers or None or have an __index__ method.
Unpacker: pdffile
```

**Comment by amadisson** [comment]
I created peepdf fork with merged fixes.  #66 
Also also creating fix for Cuckoo.
