### ISSUE TITLE
Plans to provide source code for Threemon and loader?

### ISSUE THREAD

**Issue by zaddach** [cert-ee/cuckoo3#69]
Hi,

are there any plans to provide the source code for Threemon and the loader? The current (binary) version seems to be tied to the specific Windows versions in the install manual, Having the source might allow me to port it to newer Windows versions.

Thanks for your excellent work!

**Comment by bradley-kite** [comment]
Does anyone know the origins of the Threemon driver?

**Comment by rkivistik** [comment]
We are not planning on providing the source code for Threemon and the loader.
We are however working hard to add support for more Windows versions. The exact time frame is still to be determined so stay tuned for our roadmap.
