### ISSUE TITLE
AWS Support

### ISSUE THREAD

**Issue by zkinkelaar** [cert-ee/cuckoo3#7]
I am wondering if Cuckoo3 has the ability to work in a AWS environment. Would this be something that i can set up with the current system?

**Comment by cccs-kevin** [comment]
Here is the only instance I'm aware of for Cuckoo on AWS: https://github.com/CheckPointSW/Cuckoo-AWS
I've also developed a machinery for Azure which I'm using in a production environment (https://github.com/cuckoosandbox/cuckoo/pull/3120).

That all being said, these are for Cuckoo2 :/

**Comment by rkivistik** [comment]
Unfortunately we do not have AWS support in our roadmap at this time.
