### ISSUE TITLE
MkDocs build generates errors about included pages that are not included and errors in usage/webapi/endpoints.md

### ISSUE THREAD

**Issue by Marvinus** [cert-ee/cuckoo3#70]
**Describe the bug**

when doing an "Mkdocs build" the following issues occur:
"
The following pages exist in the docs directory, but are not included in the "nav" configuration:
index.md
configuration/cuckooconfs/analysissettingsyaml.md
introduction/terminology.md

ERROR - Error reading page 'usage/webapi/endpoints.md':
ERROR - No files found including 'analysis.json' at usage/webapi/endpoints.md:321
"

The files do exist though.

**To Reproduce**
"Mkdocs build"

**Expected behavior**
a clean build

** My Cuckoo version and operating system are::**
 Cuckoo 3.0.1, Ubuntu 22.04

**The log, error, files etc can be found at:**

**Comment by geeksailor** [comment]
I just tried running the build and ran into the same error. I tried looking into it some and it may have to do with the mkdocs-include-markdown-plugin and being able to read the json? I have some other stuff I'm looking into and fixing but I plan on circling back and looking into this more to see if I can find a solution if it hasn't been resolved. Hopefully this can help someone else maybe try looking into it and finding a solution in the meantime.

**Comment by geeksailor** [comment]
That's odd because I'm running 3.8 when I got the error. But thank you for updating it @Cryss76!
Cheers!

**Comment by Cryss76** [comment]
>EDIT 2: Spoke too soon. Clicking on any link on the left menu leads to an index directory page. You have to click on a link to get to the index for those sections.

Thats normal as you're expected to run it as a server. run: `mkdocs serve` and open `localhost:8000`

**Comment by Cryss76** [comment]
if this fixed your issue @Marvinus pls close

**Comment by Cryss76** [comment]
@amadisson  pls close
