### ISSUE TITLE
yara-python error ending in ./processing failed and terminates

### ISSUE THREAD

**Issue by stabuu** [cert-ee/cuckoo3#73]
**Describe the bug**
following the steps to build out dependencies and once I get to running the ./install.sh I am getting an error when it comes to the yara-python build. the process terminates. 

I have even tried compiling it myself with no luck: 
$ git clone --recursive https://github.com/VirusTotal/yara-python
$ cd yara-python
$ python setup.py build
$ sudo python setup.py install

tried to copy the files over to the main cuckoo folder and attempted to change the versioning to 4.4.0 which I believe is the latest version. 

** My Cuckoo version and operating system are::**
 Cuckoo 3.0.1, Ubuntu 22.04

**The log, error, files etc can be found at:**
![yarapython error in install of cuckoo](https://github.com/cert-ee/cuckoo3/assets/54125697/255515db-c766-4cdd-b79f-e4a2485ff895)

**Comment by 0x4hm3d** [comment]
try to install these packge and try ./install.sh again
sudo apt install libssl-dev libffi-dev libxml2-dev libxslt1-dev libpq-dev  libldap2-dev libsasl2-dev python3.11-dev build-essential gcc

**Comment by Cryss76** [comment]
had the same problem and can confirm that @0x4hm3d's solution works.

**Comment by stabuu** [comment]
Yes thank you @0x4hm3d this solution does fix the issue with the install script! Ran into a new issues with the command lines with vmcloak I am working through.

**Comment by 0x4hm3d** [comment]
I think the error in vmclock is the version of the pefile packge, you can fix it by these steps
Edit vmcloak/setup.py and Change pefile version in install_requires to
"pefile<2023.0.0",
And run : pip install . && cd ..

**Comment by stabuu** [comment]
install was successful, but the commands to build an image are failing with syntax errors. 

what I am trying: 

vmcloak --debug init --win10x64 --hddsize 128 --cpus 2 --ramsize 4096 --network 192.168.30.0/24 --vm qemu --ip 192.168.30.2 --iso-mount /mnt/win10x64 win10base br0
![vm clock cmd line syntax errors](https://github.com/cert-ee/cuckoo3/assets/54125697/34b4e9a6-42ca-4331-b295-5870f2458dfc)

might be going about it the wrong way?

**Comment by 0x4hm3d** [comment]
Check this:
https://github.com/Cryss76/vmcloak

**Comment by stabuu** [comment]
thanks for this. It appears my original install of vmcloak wasn't clean after pulling from their github and reconfiguring their setup file it is working properly now.

**Comment by Cryss76** [comment]
> Yes thank you @0x4hm3d this solution does fix the issue...

@amadisson pls close as the issue was fixed

**Comment by shaheer-haider** [comment]
> try to install these packge and try ./install.sh again sudo apt install libssl-dev libffi-dev libxml2-dev libxslt1-dev libpq-dev libldap2-dev libsasl2-dev python3.11-dev build-essential gcc

Thank you.
