### ISSUE TITLE
Cuckoo --distributed throwing error

### ISSUE THREAD

**Issue by Rparte** [cert-ee/cuckoo3#77]
Hello team,

I have been trying to install distributed cuckoo. Successfully completed the installation of the task node, and the curl query is giving the output as mentioned in the installation document.

Updated the node ip, port, and API key in the distributed.yaml in the main node. The main node is installed with cuckoo 3 and completed steps 1-3 and 6 and 7. Upon running cuckoo --distributed it throws a network interface error and vm error. 

```
:~/.cuckoocwd$ cuckoo --distributed
2023-11-22 16:57:11 INFO  [cuckoo.startup]: Starting Cuckoo controller. cwd=/home/cuckoo3/.cuckoocwd
2023-11-22 16:57:11 INFO  [cuckoo.startup]: Loading configurations
2023-11-22 16:57:11 ERROR [cuckoo.common.log]: Failure during Cuckoo startup: Failed to load config file /home/cuckoo3/.cuckoocwd/conf/machineries/qemu.yaml. Error in config file: /home/cuckoo3/.cuckoocwd/conf/machineries/qemu.yaml. Constraint violation for key interface: Network interface 'br0' does not exist.
Stopping Cuckoo..
Failure during Cuckoo startup: Failed to load config file /home/cuckoo3/.cuckoocwd/conf/machineries/qemu.yaml. Error in config file: /home/cuckoo3/.cuckoocwd/conf/machineries/qemu.yaml. Constraint violation for key interface: Network interface 'br0' does not exist.
```

Do we need to setup VMs in the main node? And how main node will communicate with task node.

**Comment by cert-ee-raidar** [comment]
@Rparte 
You do not have your network interface up. Use VMCloak utility `vmcloak-qemubridge` to bring up the interface.
Replace the subnet with yours.
If for some reason you do not have VMCloak, get it from here - https://github.com/cert-ee/vmcloak

```console
sudo /home/cuckoo/vmcloak/bin/vmcloak-qemubridge br0 192.168.30.1/24
```

**Comment by Cryss76** [comment]
@cert-ee-raidar
I was browsing through the docs and didn't find any reference to creating and enabling the qemu bridge. Including this in the docs would be a nice improvement.

**Comment by cert-ee-raidar** [comment]
It comes from VMCloak documentation.
We have an extensive documentation overhaul in the works and will be rolling it out this month.
