### ISSUE TITLE
Failed building wheel for VMCloak

### ISSUE THREAD

**Issue by manman84** [cert-ee/cuckoo3#79]
I'm following a guide from https://reversingfun.com/posts/cuckoo-3-installation-guide/ and just installed vmcloak using `git clone https://github.com/hatching/vmcloak.git && cd vmcloak` and then I used this command `pip install . && cd ..` which gives me an error:
![cuckoo error pt1](https://github.com/cert-ee/cuckoo3/assets/154253966/a3c67288-5bb9-4586-b1b0-17090cf3aa07)
![cuckoo error pt2](https://github.com/cert-ee/cuckoo3/assets/154253966/43f6b0a0-b1d1-49c3-88af-27e902cc889a)

I have wheel installed so I'm really not sure what the problem is. Any help is appreciated thanks!

**Comment by Hamza-Megahed** [comment]
First,
Edit cuckoo3/processing/setup.py and change pefile and hyperscan version in install_requires to
```
"pefile<2023.0.0",
"hyperscan>=0.4.0",
```
and reinstall cuckoo3 again 
Second, edit vmcloak/setup.py and Change pefile version in install_requires to
` "pefile<2023.0.0",`

or follow the installation steps [here](https://www.hamza-megahed.com/cuckoo3/)
