### ISSUE TITLE
Does cuckoo3 support volatility? If not, will it?

### ISSUE THREAD

**Issue by Dar-BN** [cert-ee/cuckoo3#8]
Does cuckoo3 support analysis of memory dumps using volatility? I can't see any mention of it in the code, so guessing not.

So, is there any intention to support it? Is there a roadmap/todo list, or similar, that can be referred to to better undestand the plans and what is and isn't there yet?

**Comment by rkivistik** [comment]
Unfortunately volatility is not supported and it is not in our roadmap.
We are working on our roadmap and once it is in place, we will add it here to our Github so stay tuned.
