### ISSUE TITLE
Does cuckoo3 support snort 3?

### ISSUE THREAD

**Issue by BurnLoch** [cert-ee/cuckoo3#85]
Does Cuckoo3 support Snort? I сan't see any mentions of it in the code, only Suricata. Cuckoo Sandbox version 2 supported Snort. It's possible that support for Snort will be added later, but I haven't found a roadmap/todo list or anything similar, so it's hard to understand.

**Comment by rkivistik** [comment]
Snort support is in our roadmap.
We will share our roadmap once we have it set. Stay tuned

**Comment by cert-ee-raidar** [comment]
Duplicate of #115
