### ISSUE TITLE
MISP connection 

### ISSUE THREAD

**Issue by GreddyCZ** [cert-ee/cuckoo3#90]
**Describe the bug**
I tried to connect cuckoo with misp, but nothing happend

**To Reproduce**
i tried configure misp.yaml with tls verify on/off
API key used by curl worked - so there is not problem with Firewall

** My Cuckoo version and operating system are::**
 Cuckoo version - last version 3.0.1, Ubuntu 22.04

**The log, error, files etc can be found at:**
i cannot find any log files for this,just this 
Failed to notify state controller of new analyses. Is the main Cuckoo process ru                                                                                        nning? Failed to notify state controller of new analyses. Could not connect to s                                                                                        ocket: /home/cuckoo/.cuckoocwd/operational/sockets/statecontroller.sock. Error:                                                                                         [Errno 111] Connection refused

any help?

**Comment by rkivistik** [comment]
The line `Is the main Cuckoo process ru nning` is the clue here.
Is your Cuckoo process running? When Cuckoo is not running, state controller is not running.

**Comment by cert-ee-raidar** [comment]
@GreddyCZ did the issue get resolved for you?

**Comment by cert-ee-raidar** [comment]
Closing the issue due to inactivity
