### ISSUE TITLE
[agent] Clarification on agent.py Python Requirements

### ISSUE THREAD

**Issue by nicpenning** [cert-ee/cuckoo3#95]
What version of Python is needed for the agent.py on the Host VMs?

Running the Windows 7 iso recommended from the docs does not contain Service Pack 1 so Python 3 can't be used. This conflicts with the Python 3 recommendation for the Cuckoo host. So it seems Python 2 is required on the VM guest side.

Also, will the agent.py be moved away from this third party [repo](https://github.com/jbremer/agent) and be maintained in this one?

The link in the [docs](https://cuckoo-hatch.cert.ee/static/docs/installation/vmcreation/) direct you here: https://raw.githubusercontent.com/jbremer/agent/master/agent.py

**Comment by nicpenning** [comment]
Okay, great. Thank you!

**Comment by cert-ee-raidar** [comment]
We recommend all new VMs be made with VMCloak to bypass all agent related issues.
Please see [Creating Virtual Machines](https://cuckoo-hatch.cert.ee/static/docs/creating/vms/).
Closing the issue.
